### ISSUE TITLE
JOOQ Sync error in preview

### ISSUE THREAD

**Issue by srcChain** [cardano-foundation/cf-ledger-sync#64]
It appears there are two errors now, but I was hoping to replicate the first error (which happened 3 tiimes in preview) but could not as I encountered the new error below. The first error happened consistently on block number 110449 related to cbor parse error. Unfortunately, the error below prevented me from capturing the cbor parse error.

For some background, I am runnig Postgres 15 on Ubuntu 23.0

Distributor ID:	Ubuntu
Description:	Ubuntu 23.04
Release:	23.04
Codename:	lunar

The cardano node version is:

cardano-node 8.1.2 - linux-x86_64 - ghc-8.10
git rev d2d90b48c5577b4412d5c9c9968b55f8ab4b9767

Is there a recommended cardano-node version to use with a given version of cf-ledger-sync? No mention of this is made in the README. 

I encountered the following error while attempting to sync Preview: 

2023-11-12 18:48:18.254  INFO 901515 --- [ntLoopGroup-5-4] o.c.l.e.listeners.BlockEventListener     : Block  number 99361, slot_no 2116933, hash 152a8f68ccc0a30b800b92424830753ef56c3ce84c95d1a0f27ac6904f6b4e5d
2023-11-12 18:48:18.844  INFO 901515 --- [ntLoopGroup-5-4] o.c.l.e.listeners.BlockEventListener     : Block  number 99369, slot_no 2117085, hash af7eeab291e462d2e43d00c75bda0dc591899787133a8de8a1147111804fba6a
org.springframework.jdbc.BadSqlGrammarException: jOOQ; bad SQL grammar [select address_token_balance.id, address_token_balance.address_id, address_token_balance.balance, address_token_balance.ident, address_token_balance.stake_address_id, address.id, address.address, address.address_has_script, address.balance, address.tx_count, address.stake_address_id, address.verified_contract, multi_asset.id, multi_asset.fingerprint, multi_asset.name, multi_asset.policy, multi_asset.supply, multi_asset.tx_count, multi_asset.time, multi_asset.total_volume, multi_asset.name_view from address_token_balance join address on address_token_balance.address_id = address.id join multi_asset on address_token_balance.ident = multi_asset.id where ((address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?))]
	at org.jooq_3.18.2.POSTGRES.debug(Unknown Source)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:246)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.translate(JooqExceptionTranslator.java:94)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.handle(JooqExceptionTranslator.java:81)
	at org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator.exception(JooqExceptionTranslator.java:55)
	at org.jooq.impl.ExecuteListeners.exception(ExecuteListeners.java:304)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:372)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2838)
	at org.cardanofoundation.ledgersync.explorerconsumer.repository.custom.CustomAddressTokenBalanceRepository.findAllByAddressFingerprintPairIn(CustomAddressTokenBalanceRepository.java:55)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
	at org.cardanofoundation.ledgersync.explorerconsumer.repository.custom.CustomAddressTokenBalanceRepository$$SpringCGLIB$$0.findAllByAddressFingerprintPairIn(<generated>)
	at org.cardanofoundation.ledgersync.explorerconsumer.service.impl.AddressBalanceServiceImpl.lambda$getAddressTokenBalanceMap$11(AddressBalanceServiceImpl.java:376)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "address_token_balance" does not exist
  Position: 505
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4754)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:357)
	... 25 more
2023-11-12 18:48:19.689 ERROR 901515 --- [ntLoopGroup-5-4] o.c.l.e.listeners.BlockEventListener     : jOOQ; bad SQL grammar [select address_token_balance.id, address_token_balance.address_id, address_token_balance.balance, address_token_balance.ident, address_token_balance.stake_address_id, address.id, address.address, address.address_has_script, address.balance, address.tx_count, address.stake_address_id, address.verified_contract, multi_asset.id, multi_asset.fingerprint, multi_asset.name, multi_asset.policy, multi_asset.supply, multi_asset.tx_count, multi_asset.time, multi_asset.total_volume, multi_asset.name_view from address_token_balance join address on address_token_balance.address_id = address.id join multi_asset on address_token_balance.ident = multi_asset.id where ((address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?) or (address.address = ? and multi_asset.fingerprint = ?))]
2023-11-12 18:48:19.712  INFO 901515 --- [ionShutdownHook] c.b.c.yaci.core.network.NodeClient       : Shutdown connection !!!
2023-11-12 18:48:19.712  INFO 901515 --- [ionShutdownHook] c.b.cardano.yaci.core.network.Session    : Disposing the session !!!
2023-11-12 18:48:19.712  INFO 901515 --- [ntLoopGroup-3-1] c.b.c.yaci.core.network.NodeClient       : Connection closed !!!
2023-11-12 18:48:19.739  INFO 901515 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2023-11-12 18:48:19.743  INFO 901515 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : explorer-consumer-pool - Shutdown initiated...
2023-11-12 18:48:19.748  INFO 901515 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : explorer-consumer-pool - Shutdown completed.

**Comment by Sotatek-HuyLe3a** [comment]
Thanks @srcChain, this jooq error is relates to issue #62 , and currently, you can use branch "issue_62" to fix the jooq error before we make changes to the main branch.

**Comment by srcChain** [comment]
Thanks for your response @Sotatek-HuyLe3a ! I'll check out that branch and give it another shot. 

Cheers
