### ISSUE TITLE
cbor de-serialization error

### ISSUE THREAD

**Issue by srcChain** [cardano-foundation/cf-ledger-sync#70]
@Sotatek-HuyLe3a, here is the cbor de-serialization error i mentioned in the first issue. The env is the same. I encountered this after checking out and running issue_62 branch like you recommended. Network is preview as before:

2023-11-13 18:50:51.028  INFO 26183 --- [ntLoopGroup-5-2] c.b.c.y.s.core.service.CursorService     : # of blocks written: 11000
2023-11-13 18:50:51.028  INFO 26183 --- [ntLoopGroup-5-2] c.b.c.y.s.core.service.CursorService     : Block No: 110370  , Era: Babbage
2023-11-13 18:50:51.033  INFO 26183 --- [ntLoopGroup-5-2] o.c.l.e.listeners.BlockEventListener     : Block  number 110371, slot_no 2338497, hash 663e1a1987904650d863b706ca509a7920ab248b22c8f5c990bf686bf63b9929
2023-11-13 18:50:51.545  INFO 26183 --- [ntLoopGroup-5-2] o.c.l.e.listeners.BlockEventListener     : Block  number 110377, slot_no 2338641, hash 741784040b5886b8b2ed489f8e90ec7674ea2473d84079b53443fbe81b734f03
2023-11-13 18:50:52.141  INFO 26183 --- [ntLoopGroup-5-2] o.c.l.e.listeners.BlockEventListener     : Block  number 110385, slot_no 2338831, hash 380be731e556bfa3c25798c81301cf904c71126d272a98a02938541f66917346
2023-11-13 18:50:52.704  INFO 26183 --- [ntLoopGroup-5-2] o.c.l.e.listeners.BlockEventListener     : Block  number 110393, slot_no 2339135, hash a8216d463b1e579099bfd47802f0ffa099dd6d777b4cf1307722edaa401bac89
2023-11-13 18:50:53.292  INFO 26183 --- [ntLoopGroup-5-2] o.c.l.e.listeners.BlockEventListener     : Block  number 110401, slot_no 2339301, hash 785459563cf44c62cde00e814b7f13b69e7cb0a7013f5cf764df1b610019f70a
2023-11-13 18:50:53.855  INFO 26183 --- [ntLoopGroup-5-2] o.c.l.e.listeners.BlockEventListener     : Block  number 110409, slot_no 2339561, hash c05c4393081a80429bd0592d9232cc31432d38a16d1f9414e311a69132a0208c
2023-11-13 18:50:54.398  INFO 26183 --- [ntLoopGroup-5-2] o.c.l.e.listeners.BlockEventListener     : Block  number 110416, slot_no 2339692, hash 245f64cc76a98c37408fe9b470c65608de01bd7ba2770fc7433f0c0f7523af77
2023-11-13 18:50:54.907  INFO 26183 --- [ntLoopGroup-5-2] o.c.l.e.listeners.BlockEventListener     : Block  number 110420, slot_no 2339839, hash 008ce12593069433c23ea1074ab859f1ce5c25a5552652831200c9a5972c04a6
2023-11-13 18:50:55.424  INFO 26183 --- [ntLoopGroup-5-2] o.c.l.e.listeners.BlockEventListener     : Block  number 110429, slot_no 2340012, hash d51d93f6de8570a40e72cb511d2e92c65d31f7e3547988653131aa135364e5fe
2023-11-13 18:50:55.962  INFO 26183 --- [ntLoopGroup-5-2] o.c.l.e.listeners.BlockEventListener     : Block  number 110445, slot_no 2340203, hash 324504cc8e34d908b598fca2fecc903ce194bc736c4ea33bc94db3c8130f2f2f
com.bloxbean.cardano.client.exception.CborRuntimeException: Cbor de-serialization error
	at com.bloxbean.cardano.client.common.cbor.CborSerializationUtil.deserialize(CborSerializationUtil.java:187)
	at org.cardanofoundation.ledgersync.explorerconsumer.util.RedeemerWrapper.<init>(RedeemerWrapper.java:18)
	at org.cardanofoundation.ledgersync.explorerconsumer.service.impl.RedeemerServiceImpl.lambda$handleRedeemers$3(RedeemerServiceImpl.java:66)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.cardanofoundation.ledgersync.explorerconsumer.service.impl.RedeemerServiceImpl.handleRedeemers(RedeemerServiceImpl.java:67)
	at org.cardanofoundation.ledgersync.explorerconsumer.service.impl.TransactionServiceImpl.handleTxContents(TransactionServiceImpl.java:190)
	at org.cardanofoundation.ledgersync.explorerconsumer.service.impl.TransactionServiceImpl.handleTxs(TransactionServiceImpl.java:146)
	at org.cardanofoundation.ledgersync.explorerconsumer.service.impl.TransactionServiceImpl.prepareAndHandleTxs(TransactionServiceImpl.java:135)
	at org.cardanofoundation.ledgersync.explorerconsumer.service.impl.block.BlockSyncServiceImpl.handleBlockSync(BlockSyncServiceImpl.java:78)
	at org.cardanofoundation.ledgersync.explorerconsumer.service.impl.block.BlockSyncServiceImpl.startBlockSyncing(BlockSyncServiceImpl.java:50)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at io.micrometer.core.aop.TimedAspect.processWithTimer(TimedAspect.java:227)
	at io.micrometer.core.aop.TimedAspect.perform(TimedAspect.java:202)
	at io.micrometer.core.aop.TimedAspect.timedMethod(TimedAspect.java:194)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:637)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:71)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
	at org.cardanofoundation.ledgersync.explorerconsumer.service.impl.block.BlockSyncServiceImpl$$SpringCGLIB$$0.startBlockSyncing(<generated>)
	at org.cardanofoundation.ledgersync.explorerconsumer.listeners.BlockEventListener.handleAggregateBlock(BlockEventListener.java:159)
	at org.cardanofoundation.ledgersync.explorerconsumer.listeners.BlockEventListener.handleBlockEvent(BlockEventListener.java:56)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
	at org.cardanofoundation.ledgersync.explorerconsumer.listeners.BlockEventListener$$SpringCGLIB$$0.handleBlockEvent(<generated>)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:348)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:233)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:174)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:437)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at com.bloxbean.cardano.yaci.store.core.service.BlockFetchService.onBlock(BlockFetchService.java:110)
	at com.bloxbean.cardano.yaci.helper.listener.BlockFetchAgentListenerAdapter.blockFound(BlockFetchAgentListenerAdapter.java:62)
	at com.bloxbean.cardano.yaci.core.protocol.blockfetch.BlockfetchAgent.lambda$onReceiveBlocks$4(BlockfetchAgent.java:134)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at com.bloxbean.cardano.yaci.core.protocol.blockfetch.BlockfetchAgent.onReceiveBlocks(BlockfetchAgent.java:134)
	at com.bloxbean.cardano.yaci.core.protocol.blockfetch.BlockfetchAgent.processResponse(BlockfetchAgent.java:83)
	at com.bloxbean.cardano.yaci.core.protocol.Agent.receiveResponse(Agent.java:44)
	at com.bloxbean.cardano.yaci.core.network.handlers.MiniProtoClientInboundHandler.channelRead(MiniProtoClientInboundHandler.java:39)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:349)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: co.nstant.in.cbor.CborException: Unexpected end of stream
	at co.nstant.in.cbor.decoder.MapDecoder.decodeInfinitiveLength(MapDecoder.java:38)
	at co.nstant.in.cbor.decoder.MapDecoder.decode(MapDecoder.java:21)
	at co.nstant.in.cbor.CborDecoder.decodeNext(CborDecoder.java:134)
	at co.nstant.in.cbor.decoder.ArrayDecoder.decodeInfinitiveLength(ArrayDecoder.java:33)
	at co.nstant.in.cbor.decoder.ArrayDecoder.decode(ArrayDecoder.java:21)
	at co.nstant.in.cbor.CborDecoder.decodeNext(CborDecoder.java:130)
	at co.nstant.in.cbor.CborDecoder.decodeNext(CborDecoder.java:145)
	at co.nstant.in.cbor.decoder.ArrayDecoder.decodeFixedLength(ArrayDecoder.java:50)
	at co.nstant.in.cbor.decoder.ArrayDecoder.decode(ArrayDecoder.java:23)
	at co.nstant.in.cbor.CborDecoder.decodeNext(CborDecoder.java:130)
	at co.nstant.in.cbor.CborDecoder.decode(CborDecoder.java:90)
	at co.nstant.in.cbor.CborDecoder.decode(CborDecoder.java:78)
	at com.bloxbean.cardano.client.common.cbor.CborSerializationUtil.deserialize(CborSerializationUtil.java:185)
	... 102 more
2023-11-13 18:50:56.190 ERROR 26183 --- [ntLoopGroup-5-2] o.c.l.e.listeners.BlockEventListener     : Cbor de-serialization error
2023-11-13 18:50:56.207  INFO 26183 --- [ionShutdownHook] c.b.c.yaci.core.network.NodeClient       : Shutdown connection !!!
2023-11-13 18:50:56.207  INFO 26183 --- [ionShutdownHook] c.b.cardano.yaci.core.network.Session    : Disposing the session !!!
2023-11-13 18:50:56.208  INFO 26183 --- [ntLoopGroup-3-1] c.b.c.yaci.core.network.NodeClient       : Connection closed !!!
2023-11-13 18:50:56.232  INFO 26183 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2023-11-13 18:50:56.236  INFO 26183 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : explorer-consumer-pool - Shutdown initiated...
2023-11-13 18:50:56.241  INFO 26183 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : explorer-consumer-pool - Shutdown completed.

Thanks

**Comment by satran004** [comment]
Hi @srcChain, Thanks for trying this out.

We are looking into this issue.
FYI, we are in the process of migrating Ledger Sync from our previous internal implementation to a new design to simplify the architecture and setup process. However, we hope to create a release tag soon once we have a stable version.

**Comment by srcChain** [comment]
Awesome! Please let me know when I can check it out when its available.

Thanks

**Comment by satran004** [comment]
Hi @srcChain,
 
We have merged a fix for this issue into the main branch and tested it with the preview network. It seems to be ok now, so you can give it a try.

Let us know if you find any issues.

FYI, the sync process is a little slow now, but we are working on a solution to fix that.

**Comment by srcChain** [comment]
Thanks for the heads up @satran004! I'll give it a try over the weekend and keep you posted.

Much appreciated!

**Comment by srcChain** [comment]
FYI - just wanted to report back that the main branch worked perfectly! My preview node is fully synced and there were no issues whatsoever!

Great job guys!

Cheers!

**Comment by satran004** [comment]
Thanks @srcChain for the confirmation.
